name: Testing Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Create .env file
        run: touch .env
          echo DSN=${{ secrets.API_KEY }} >> .env
          cat .env

      - name: Run
        run: go run cmd/main.go
