name: Go

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Test env var
      env:
        TEST: "Test env var"
        DSN: ${{secrets.DSN}}
      run: echo $TEST $DSN

    - name: Run
      run: go run cmd/main.go
