name: Go

on: push

env:
  TEST: "Test env var"
  DSN: ${{secrets.DSN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Test env var
      run: echo $TEST $DSN

    - name: Run
      run: go run cmd/main.go
